pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -f ConfigServer/pom.xml -DoutputDirectory=~/configServer -B -DskipTests clean package'
                
            }
        }
        stage('Deploy') { 
            steps {
				// sh 'PM2_HOME=\'/home/ubuntu/.pm2\' pm2 delete configServer'
            	dir('/home/ubuntu/') {
            		echo 'Destruindo instancia atual e apagando .jar'
            		sh './destroyConfigServerInstance.sh'
            		echo 'Instancia destruida'
            		echo 'Deletando .jar antigo'
            		sh 'removeConfigServerJar.sh'
            		echo 'Copiando .jar novo para pasta definitiva'
            		sh 'cp /var/lib/jenkins/workspace/Config-server/ConfigServer/target/ConfigServer*.jar /home/ubuntu/configServer/configServer.jar'
            		echo 'Jar copiado com sucesso'
            		echo 'Subindo instancia nova'
					sh './runConfigServer.sh'
					echo 'Instancia nova executada com sucesso'
				}
            }
        }
    }
    // post {
	//	success {
	//		echo 'Esteira finalizada com sucesso!'
     //   }
	//	failure {
	//		echo 'Esteira falhou...'
     //   }
    // }
}