pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -f ConfigServer/pom.xml -DoutputDirectory=~/configServer -B -DskipTests clean package'
                
            }
        }
        stage('Deploy') { 
            steps {
            	// dir('/home/ubuntu/') {
					sh 'PM2_HOME=\'/home/ubuntu/.pm2\' pm2 delete configServer'
					sh './runConfigServer.sh'
				// }
            }
        }
    }
    post {
		success {
			echo 'Esteira finalizada com sucesso!'
        }
		failure {
			echo 'Esteira falhou...'
        }
    }
}