pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh 'mvn --version'
            }
        }
        stage('Deploy') { 
            steps {
                sh 'echo Hello World' 
            }
        }
    }
}